base_url = "https://tversteeg.nl"

title = "Thomas Versteeg"

compile_sass = true

build_search_index = true

generate_rss = true

theme = "sam"

taxonomies = [
    {name = "tags", rss = true}
]

[markdown]
highlight_code = true

[extra]
sam_menu = [
    { text = "ld46", link = "/ld46" },
    { text = "posts", link = "/posts" },
    { text = "whoami", link = "/about" },
    { text = "github", link = "https://github.com/tversteeg" },
    { text = "email", link = "mailto:t@versteeg.email" }
]

sam_bottom_menu = true

show_word_count = true
show_reading_time = true

date_format = "%d-%b-%Y"
