base_url = "https://tversteeg.nl"

title = "Thomas Versteeg"
author = "Thomas Versteeg"

theme = "after-dark"

compile_sass = true
generate_feed = true

taxonomies = [
    {name = "tags", feed = true}
]

[markdown]
highlight_code = true

[extra]
after_dark_menu = [
    { name = "home", url = "/" },
    { name = "whoami", url = "/about" },
    { name = "tags", url = "/tags" },
    { name = "github", url = "https://github.com/tversteeg" },
    { name = "itch.io", url = "https://tversteeg.itch.io" },
    { name = "email", url = "mailto:t@versteeg.email" }
]

after_dark_title = "Posts"

show_word_count = true
show_reading_time = true

date_format = "%d-%b-%Y"
