base_url = "https://tversteeg.nl"

title = "Thomas Versteeg"
author = "Thomas Versteeg"

theme = "after-dark"

compile_sass = true
generate_feed = true

taxonomies = [
    {name = "tags", feed = true}
]

[markdown]
highlight_code = true

[extra]
after_dark_menu = [
    { name = "home", url = "$BASE_URL" },
    { name = "ld46", url = "$BASE_URL/ld46" },
    { name = "whoami", url = "$BASE_URL/about" },
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "github", url = "https://github.com/tversteeg" },
    { name = "email", url = "mailto:t@versteeg.email" }
]

after_dark_title = "Posts"

show_word_count = true
show_reading_time = true

date_format = "%d-%b-%Y"
